create feature branch
Ilya-m2195/frontend_3 pull request #1
Opened 2024-01-19 14:20 UTC by Ilya-m2195

2024-01-26 07:24 UTC, AdammmVV commented on src/components/layout/UserEditing/UserEditing.tsx
> +          form.reset();
take logic out of markup

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/AddUserNickForm/AddUserNickForm.tsx
> +        })}
take logic out of markup

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/AddUsersForm/AddUsersForm.tsx
> +        })}
take logic out of markup

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/AddUsersForm/AddUsersForm.tsx
> +          </span>
use components from mantine

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/ErrorMessage/ErrorMessage.tsx
> +    </div>
use components from mantine

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/SwitchButton/SwitchButton.tsx
> +  const dark = 'dark';
put this in config and create Enum

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/SwitchButton/SwitchButton.tsx
> +const yellowValue = 4;
put this in constants

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/SwitchLanguageBtn/SwitchLanguageBtn.tsx
> +  const ru = 'ru';
put this in config and create Enum

2024-01-26 07:24 UTC, AdammmVV commented on src/constants/constants.ts
> +export const errorMessageEmptyField = 'Заполните поле';
put it in translate

2024-01-26 07:24 UTC, AdammmVV commented on src/hooks/useSortableData.ts
> +      sortableItems.sort((a, b) => {
use clear names

2024-01-26 07:24 UTC, AdammmVV commented on src/hooks/useSortableData.ts
> +          return sortConfig.direction === 'ascending' ? -1 : 1;
use Enum for `ascending, descending`

2024-01-26 07:24 UTC, AdammmVV commented on src/hooks/useSortableData.ts
> +  items: Array<any>,
don`t use any

2024-01-26 07:24 UTC, AdammmVV commented on src/hooks/useSortableData.ts
> +  config: IConfig | null = null,
what is this for? `null = null`

2024-01-26 07:24 UTC, AdammmVV commented on src/hooks/useSortableData.ts
> +  items: Array<any>;
don`t use any

2024-01-26 07:24 UTC, AdammmVV commented on src/i18n.ts
> +    fallbackLng: 'en',
se Enum and reuse `'en'`

2024-01-26 07:24 UTC, AdammmVV commented on src/store/slices/mainSlice.ts
> +  async (_, config) => {
if you are using ThunkApi, try using destructuring `config`

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/Navigation/Navigation.tsx
> +  const itemStyle = 'item';
use Enum for this

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/LoaderFC/LoaderFC.tsx
> +  return <Loader className='loader' color='indigo' />;
use module.css `className='loader'`

2024-01-26 07:24 UTC, AdammmVV commented on src/components/shared/ErrorMessage/ErrorMessage.tsx
> +    <div className='errorMessageBlock'>
use module.css `className='errorMessageBlock'` and use mantine components

2024-01-26 07:24 UTC, AdammmVV commented on src/components/layout/Users/Users.tsx
> +    <div>
use mantine components

2024-01-26 07:24 UTC, AdammmVV commented on src/components/layout/Home/Home.tsx
> +    </div>
use mantine components

2024-01-26 07:24 UTC, AdammmVV commented on src/App.tsx
> +        </Routes>
try use [createBrowserRouter](https://reactrouter.com/en/main/start/overview#client-side-routing)

2024-01-26 07:24 UTC, AdammmVV commented on package.json
>    "version": "0.1.0",
why didn't use Vite React instead of CRA

2024-01-28 13:05 UTC, suveiko commented on src/App.tsx
>    const isLoading = useAppSelector((state) => state.main.isLoading);
create separate file for selectors, for example: 
`
const getIsLoading = (state: RootState): boolean => state.main.isLoading

usage: 
const isLoading = useAppSelector(getIsLoading)
`

2024-01-28 13:06 UTC, suveiko commented on src/components/layout/Home/Home.tsx
>    const email = useAppSelector((state) => state.main.email);
also move to selectors

2024-01-28 13:10 UTC, suveiko commented on src/components/layout/UserEditing/UserEditing.tsx
> +      <form onSubmit={form.onSubmit((values) => onSubmitHandler(values))}>
`form.onSubmit(onSubmitHandler)`

2024-01-28 13:11 UTC, suveiko commented on src/components/shared/AddUserNickForm/AddUserNickForm.tsx
> +        fullName: values.fullName,
`      role,
        nickname,
        balance,
        phone,
        fullName,
`

2024-01-28 13:13 UTC, suveiko commented on src/components/shared/AddUserNickForm/AddUserNickForm.tsx
> +  const onSubmitHandler = (values: IValues): void => {
({ role, nickname, balance, phone, fullName }: IValues)

2024-01-28 13:16 UTC, suveiko commented on src/components/shared/AddUserNickForm/AddUserNickForm.tsx
> +      <form onSubmit={form.onSubmit((values) => onSubmitHandler(values))}>
<form onSubmit={form.onSubmit(onSubmitHandler)}>

2024-01-28 13:17 UTC, suveiko commented on src/components/shared/AddUsersForm/AddUsersForm.tsx
> +    console.log(values);
remove log

2024-01-28 13:17 UTC, suveiko commented on src/components/shared/AddUsersForm/AddUsersForm.tsx
> +      <form onSubmit={form.onSubmit((values) => onSubmitHandler(values))}>
`<form onSubmit={form.onSubmit(onSubmitHandler)}>`

2024-01-28 13:18 UTC, suveiko commented on src/components/shared/Navigation/Navigation.tsx
> +        }
move to variable

2024-01-28 13:18 UTC, suveiko commented on src/components/shared/Navigation/Navigation.tsx
>          onClick={() => setCurrentLinkHandler(pathHome)}
move outside to separate function

2024-01-28 13:18 UTC, suveiko commented on src/components/shared/Navigation/Navigation.tsx
> +              : NamesActiveStyles.itemStyle
move to variable

2024-01-28 13:18 UTC, suveiko commented on src/components/shared/Navigation/Navigation.tsx
>            onClick={() => setCurrentLinkHandler(pathUsers)}
move to separate function

2024-01-28 13:51 UTC, suveiko commented on src/components/shared/SwitchLanguageBtn/SwitchLanguageBtn.tsx
>        onChange={(e: ChangeEvent<HTMLSelectElement>) => changeLanguageHandler(e)}
`onChange={changeLanguageHandler}`

2024-01-28 17:05 UTC, remadyt requested changes

2024-01-28 17:05 UTC, remadyt commented on package.json
> +    "vite": "^5.0.12",
i think its' dev depend

2024-01-28 17:05 UTC, remadyt commented on package.json
> +    "@vitejs/plugin-react": "^4.2.1",
i think its' dev depend

2024-01-28 17:05 UTC, remadyt commented on package.json
> +    "vite-tsconfig-paths": "^4.3.1",
i think its' dev depend

2024-01-28 17:05 UTC, remadyt commented on package.json
>      "web-vitals": "^2.1.0"
this not needed with vite

2024-01-28 17:05 UTC, remadyt commented on src/App.tsx
> +import { LoaderFC } from './components/shared/LoaderFC/LoaderFC';
why need FC in namin?

2024-01-28 17:05 UTC, remadyt commented on src/api/api.ts
> +export const LogInUser = async (
why big first letter?

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/LoginPage/LoginPage.tsx
> +
remove empty line

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/UserEditing/UserEditing.tsx
> +  };
add empty line after

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/UserEditing/UserEditing.tsx
> +  const dispatch = useAppDispatch();
separate hooks by logic, here and all such places

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/UserEditing/UserEditing.tsx
> +interface IValues {
move to types.ts here and all such places. only props in component file

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/UserEditing/UserEditing.tsx
> +  const form = useForm({
useForm<IValues>

2024-01-28 17:05 UTC, remadyt commented on src/components/layout/Users/Users.tsx
> +import { useAppDispatch } from '../../../hooks/useAppDispatch';
use absolute paths, need put in tsconfig baseUrl: 'src'

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/AddUsersForm/AddUsersForm.tsx
> +            mb={MARGIN_16}
for margin const not needed, use variable, 'xs', 'm'

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/ButtonSort/ButtonSort.tsx
> +import React from 'react';
react import not needed

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/ButtonSort/ButtonSort.tsx
> +  const requestSortHandler = (): void => requestSort(nameField);
add {}

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/LoaderFC/LoaderFC.tsx
> +import React from 'react';
same, remove here and all such places

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/Navigation/Navigation.tsx
> +  const currentClassName =
use clsx library

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/Navigation/Navigation.tsx
> +            currentLink === pathUsers
use isAcitve in NavLink component

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/SwitchButton/SwitchButton.tsx
> +  const setDark = (): void => setColorScheme(ColorTheme.dark);
refactor with 1 function

2024-01-28 17:05 UTC, remadyt commented on src/components/shared/SwitchButton/SwitchButton.tsx
> +      style={{ width: rem(sizeValue), height: rem(sizeValue) }}
do not use inline styles

2024-01-28 17:05 UTC, remadyt commented on src/store/slices/mainSlice.ts
> +  'mainSlice/logOutUser',
why need prefix main Slice?

2024-01-28 17:05 UTC, remadyt commented on src/store/slices/mainSlice.ts
> +      const result = await getUsers();
get all users for check nickname it's bad, why u not use checkValueExist?

2024-01-28 17:05 UTC, remadyt commented on src/store/slices/mainSlice.ts
> +      return rejectWithValue(error);
add errorHandler to all catch block

2024-01-28 17:05 UTC, remadyt commented on src/store/store.ts
> +    main: mainReducer,
use more informative name

2024-01-28 17:05 UTC, remadyt commented on yarn.lock
remove yarn lock. use npm or yarn, not together

2024-02-01 20:02 UTC, AdammmVV commented on src/store/slices/mainSlice.ts
> +    builder.addCase(logOutUserThank.pending, (state) => {
try using [addMatcher](https://redux-toolkit.js.org/api/createreducer#builderaddmatcher) for the same thunk

2024-02-01 20:02 UTC, AdammmVV commented on src/store/slices/mainSlice.ts
> +    });
why don't you handle errors from rejectWithValue(error)

2024-02-01 20:02 UTC, AdammmVV commented on src/components/shared/auth/LogOutUser.tsx
> +    <Button variant='outline' color='rgba(99, 99, 99, 1)' onClick={logOutHandler}>
use color from theme

2024-02-01 20:02 UTC, AdammmVV commented on src/components/shared/ErrorMessage/ErrorMessage.tsx
> +    </Title>
you need to make sure that the error text is displayed and not a stub

2024-02-01 20:02 UTC, AdammmVV commented on src/components/shared/SwitchLanguageBtn/SwitchLanguageBtn.tsx
> +  };
need to save to local storage

2024-02-01 20:02 UTC, AdammmVV commented on src/components/shared/UsersTable/UsersTable.tsx
> +  const rows = sortUsers.map((element) => (
use more informative name for `element`

2024-02-01 20:12 UTC, AdammmVV commented on src/App.tsx
> +          </Route>
add rout for error hendle in rout `error 404`

2024-02-07 10:28 UTC, merged