feat: create methods for work DB and page to shop
Ilya-m2195/frontend_3 pull request #11
Opened 2024-03-07 15:59 UTC by Ilya-m2195

2024-03-07 20:25 UTC, Egorkostuck commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +        <Modal opened={opened} onClose={close} title={t('addCategory')} centered>
I believe that custom modal logic is unnecessary. Pull changes from devs and there is already 1 global modal to which you need to pass child components. We use in the project modal manager https://mantine.dev/x/modals/

2024-03-07 20:25 UTC, Egorkostuck commented on src/components/shared/productsModal/ProductsModal.tsx
> +        <Modal opened={opened} onClose={close} title={t('addProduct')} centered>
Here too, we don't need to create so many different modals, since it's all stored in the DOM, and you should try to keep the house as small as possible. We only need to create a component that is passed to the modal.

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +  const setCategoryIdHandler = (id: string | undefined): void => {
I think a blank line is needed here to separate the variables from the function

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +    if (typeof id === 'undefined') {
Maybe this is where we should use ?
if(!id) return;

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +    if (typeof id === 'undefined') {
Maybe this is where we should use ?
if(!id) return;

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +                  <CategoriesModal id={category.id!} />
Do I understand correctly that if there is no id this modal should not be render at all? If that's the case, why not replace it with the next sparrow? `{ category.id && <CategoriesModal id={category.id} /> }` ?

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +        {productCategories && <CategoriesModal id={null} />}
What is the purpose of passing null here? Can we somehow change this logic?

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +                key={product.productName}
Will this be a unique name value? since if not, will it affect optimization? I think it is better to use id as it should be 100% unique.

2024-03-07 20:25 UTC, Egorkostuck commented on src/pages/shop/ShopPage.tsx
> +          <ProductsModal id={null} oldProductValues={null} />
Should we render this modal if id values = null and oldProductValues={null} ? Can we change this logic?

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/shopSlice.ts
> +} from '../../../api';
'../../../api' => 'api'

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/shopSlice.ts
> +import { logOutUserThank, ThunkApiConfig } from '../mainSlice';
import { NamesDBCollection } from '../../../constants'; =>constants
import { handleError } from '../../../helpers'; =>helpers
import { IUniversalObjectArguments } from '../../../types'; =>types
import { logOutUserThank, ThunkApiConfig } from '../mainSlice'; =>mainSlice

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/shopSlice.ts
> +        updateShopDataThunk.pending,
https://prnt.sc/nveJqTw-nCrh It is better to put the methods separately. https://prnt.sc/yBwpbklM9T34

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/shopSlice.ts
> +        updateShopDataThunk.fulfilled,
See comment above

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/shopSlice.ts
> +        updateShopDataThunk.rejected,
See comment above

2024-03-07 20:25 UTC, Egorkostuck commented on src/store/slices/shopSlice/types.ts
> +import { NamesDBCollection } from '../../../constants';
'../../../constants' => 'constants'

2024-03-07 21:27 UTC, AdammmVV commented on src/api/api.ts
> +    await setDoc(newDocumentRef, { id: newDocumentRef.id, ...values });
it's not clear what this is for

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +  const onSubmitHandler = (values: IProductCategory): void => {
use `typeof form.velues` for value

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +  const form = useForm({
use use destructuring for form

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +    form.reset();
reset after dispatch

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +    }
try not to use else try 
```
if (!id) {
...

return
}
```

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +
remove emty line

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +    currentUserRole === UserRole.Admin && (
try to create a custom hook for this, so that it checks the role and returns isAdmin, isUser.....

Put it in shared

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/navigation/Navigation.tsx
> +        shop
translate

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/navigation/Navigation.tsx
>        {currentUserRole === UserRole.Admin && (
custom hook for this

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/productsModal/ProductsModal.tsx
> +
remove emty line

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/productsModal/ProductsModal.tsx
> +        productName: oldProductValues.productName,
try
```suggestion
    productName: oldProductValues?.productName || '',
```

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/productsModal/ProductsModal.tsx
> +  const form = useForm({
use use destructuring for form

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/productsModal/ProductsModal.tsx
> +  const onSubmitHandler = (values: IProduct): void => {
use typeof form.velues for value

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/productsModal/ProductsModal.tsx
> +    form.reset();
reset after dispatch

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +
remove emty line

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +      {currentUserRole === UserRole.Admin && (
custom hook

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +
write typing for the component in the component

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +              id={id!}
do not use `!` 
try to set the typing correctly

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +        <Button radius='md' style={{ flex: 1 }}>
do not use inline styles

2024-03-07 21:27 UTC, AdammmVV commented on src/components/shared/shopCard/ShopCard.tsx
> +          Add to Basket
translste

2024-03-07 21:27 UTC, AdammmVV commented on src/pages/shop/ShopPage.tsx
> +  const setCategoryIdHandler = (id: string | undefined): void => {
try
```suggestion
    const setCategoryIdHandler = (id?: string): void => {
```

2024-03-07 21:27 UTC, AdammmVV commented on src/pages/shop/ShopPage.tsx
> +  const removeCategoryHandler = (id: string | undefined): void => {
try
```suggestion
   const removeCategoryHandler = (id?: string): void => {
```

2024-03-07 21:27 UTC, AdammmVV commented on src/pages/shop/ShopPage.tsx
> +          return (
`return` can be removed

2024-03-07 21:27 UTC, AdammmVV commented on src/pages/shop/ShopPage.tsx
> +            return (
`return` can be removed

2024-03-07 21:27 UTC, AdammmVV commented on src/store/slices/shopSlice/shopSlice.ts
> +  error: Nullable<string | undefined>;
try
```suggestion
 error?: Nullable<string>;
```

2024-03-08 09:22 UTC, Ilya-m2195 commented on src/api/api.ts
> +    await setDoc(newDocumentRef, { id: newDocumentRef.id, ...values });
If the ID does not come into the function, then we create a new document and add the ID value to the corresponding field. I think it's clearer and easier to understand

2024-03-08 09:33 UTC, Ilya-m2195 commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +    }
if (id) {
      dispatch(
        updateShopDataThunk({
          id,
          values,
          NamesDBCollection: NamesDBCollection.ProductCategories,
        }),
      );

      form.reset();

      return;
    }
    dispatch(setProductCategoryThunk(values));
    form.reset();
  };

I removed ELSE, but now it turns out to be a duplicate  form.reset();

2024-03-08 09:37 UTC, Ilya-m2195 commented on src/components/shared/categoriesModal/CategoriesModal.tsx
> +  const form = useForm({
For what?

2024-03-17 09:28 UTC, remadyt requested changes

2024-03-17 09:28 UTC, remadyt commented on src/components/shared/avatarProfile/AvatarProfile.tsx
> +      onConfirm: () => removeAvatar(),
onConfirm: removeAvatar

2024-03-17 09:28 UTC, remadyt commented on src/components/shared/avatarProfile/AvatarProfile.tsx
> +        <FileButton onChange={(file) => uploadFile(file)} accept={accept}>
onChange={uploadFile}

2024-03-17 09:28 UTC, remadyt commented on src/components/shared/avatarProfile/AvatarProfile.tsx
> +          <IconTrash style={{ width: rem('14') }} stroke={1.5} />
do not use inline styles, here and all such places

2024-03-17 09:28 UTC, remadyt commented on src/components/shared/avatarProfile/config.ts
> +export const accept = 'image/png,image/jpeg';
use SNACK_CASE for exported contants

2024-03-17 16:43 UTC, closed without merging